Controllers/DictionaryEntriesController.cs
using Dictionary.Models;
using Dictionary.Models.Entities;
using System.Data.Entity;
using System.Net;
using System.Threading.Tasks;
using System.Web.Mvc;

namespace Dictionary.Controllers
{
    [Authorize(Roles = "admin")]
    public class DictionaryEntriesController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: DictionaryEntries
        public async Task<ActionResult> Index()
        {
            var dictionaryEntries = db.DictionaryEntries.Include(d => d.Dictionary);
            return View(await dictionaryEntries.ToListAsync());
        }

        // GET: DictionaryEntries/Details/5
        public async Task<ActionResult> Details(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            DictionaryEntry dictionaryEntry = await db.DictionaryEntries.FindAsync(id);
            if (dictionaryEntry == null)
            {
                return HttpNotFound();
            }
            return View(dictionaryEntry);
        }

        // GET: DictionaryEntries/Create
        public ActionResult Create()
        {
            ViewBag.DictionaryId = new SelectList(db.Dictionaries, "Id", "Name");
            return View();
        }

        // POST: DictionaryEntries/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "Id,DictionaryId,Word,Meaning")] DictionaryEntry dictionaryEntry)
        {
            if (ModelState.IsValid)
            {
                db.DictionaryEntries.Add(dictionaryEntry);
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }

            ViewBag.DictionaryId = new SelectList(db.Dictionaries, "Id", "Name", dictionaryEntry.DictionaryId);
            return View(dictionaryEntry);
        }

        // GET: DictionaryEntries/Edit/5
        public async Task<ActionResult> Edit(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            DictionaryEntry dictionaryEntry = await db.DictionaryEntries.FindAsync(id);
            if (dictionaryEntry == null)
            {
                return HttpNotFound();
            }
            ViewBag.DictionaryId = new SelectList(db.Dictionaries, "Id", "Name", dictionaryEntry.DictionaryId);
            return View(dictionaryEntry);
        }

        // POST: DictionaryEntries/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "Id,DictionaryId,Word,Meaning")] DictionaryEntry dictionaryEntry)
        {
            if (ModelState.IsValid)
            {
                db.Entry(dictionaryEntry).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            ViewBag.DictionaryId = new SelectList(db.Dictionaries, "Id", "Name", dictionaryEntry.DictionaryId);
            return View(dictionaryEntry);
        }

        // GET: DictionaryEntries/Delete/5
        public async Task<ActionResult> Delete(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            DictionaryEntry dictionaryEntry = await db.DictionaryEntries.FindAsync(id);
            if (dictionaryEntry == null)
            {
                return HttpNotFound();
            }
            return View(dictionaryEntry);
        }

        // POST: DictionaryEntries/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(long id)
        {
            DictionaryEntry dictionaryEntry = await db.DictionaryEntries.FindAsync(id);
            db.DictionaryEntries.Remove(dictionaryEntry);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Views/Shared/_Admin.cshtml
<!DOCTYPE html>
@{
    ViewBag.Title = "Admin";
}

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
</head>
<body>
    <div>
        @RenderBody()
    </div>
</body>
</html>


@*@Html.Partial("~/Views/Languages/Index.cshtml")*@

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <title>@ViewBag.Title - ASP.NET Dictionary</title>
    <link href="~/favicon.ico" rel="shortcut icon" type="image/x-icon" />
    <meta name="viewport" content="width=device-width, initial-scale=1">
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>

@{
    var isAdmin = User.Identity.IsAuthenticated && User.IsInRole("admin");
}

<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container">
        <a class="navbar-brand" href="#">ASP.NET Dictionary</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">

            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    @Html.ActionLink("Home", "Index", "Home", new { area = "" }, new { @class = "nav-link" })
                </li>
                @if (isAdmin)
                {
                    <li class="nav-item">
                        @Html.ActionLink("Admin", "Index", "Admin", new { area = "" }, new { @class = "nav-link" })
                    </li>
                    <li class="nav-item">
                        @Html.ActionLink("Language", "Index", "Language", new { area = "" }, new { @class = "nav-link" })
                    </li>
                    <li class="nav-item">
                        @Html.ActionLink("Dictionary", "Index", "Dictionary", new { area = "" }, new { @class = "nav-link" })
                    </li>
                    <li class="nav-item">
                        @Html.ActionLink("Vocabulary", "Index", "DictionaryEntries", new { area = "" }, new { @class = "nav-link" })
                    </li>
                }
                <li class="nav-item">
                    @Html.ActionLink("API", "Index", "Help", new { area = "HelpPage" }, new { @class = "nav-link" })
                </li>
            </ul>
            @Html.Partial("_LoginPartial")
        </div>
    </div>
</nav>

<script>

</script>

<div class="container body-content">
    @RenderBody()
    @RenderSection("SPAViews", required: false)
    <hr/>
    <footer>
        <p>&copy; @DateTime.Now.Year - Powered by ASP.NET 4.8</p>
    </footer>
</div>

@Scripts.Render("~/bundles/jquery")
@Scripts.Render("~/bundles/bootstrap")
@Scripts.Render("~/bundles/popper")
@RenderSection("Scripts", required: false)
</body>
</html>